```yaml
nameOverride: gateway
global:
  domainName: example.com
  defaultRegistry: docker.repository.axway.com/apigateway-docker-prod/7.7
  imagePullPolicy: Always
  imagePullSecrets:
  - name: regcred
  storage:
    provisioningType: "dynamic"
    storageClassName: "nfs-client"
    volumes:
      - name: events
        enabled: true
        usedBy:
          - anm
          - apimgr
          - traffic
        accessModes:
          - ReadWriteMany
        capacity: 1Mi
      - name: anm-external-config
        enabled: true
        usedBy:
          - anm
        accessModes:
          - ReadWriteMany
        capacity: 2Mi
  initContainers:
    securityContext:
      runAsNonRoot: false
  database:
    host: mysql.metrics.svc.cluster.local
    metrics:
      enabled: true
      username: "root"
      password: "password"
  cassandra:
    enabled: true
    hosts:
      - variable: CASS_HOST
        hostname: cassandra.cassandra.svc.cluster.local
    username: cassandra
    password: cassandra
    keyspace: ks
    tkeyspace: tks

anm:
  image:
    repository: "admin-nodemanager"
    tag: "7.7.0.20221130-3-BN0009-ubi7"
  resources:
    limits:
      memory: "2048Mi"
      cpu: "1000m"
    requests:
      memory: "1Gi"
      cpu: "250m"
  securityContext:
    runAsNonRoot: false
  route:
    enabled: false
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: anm.myexample.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - anm.myexample.com
  service:
    port: 8091
  extraVolumeMounts:
    - name: events
      mountPath: /opt/Axway/apigateway/events
  extraVolumes:
    - persistentVolumeClaim:
        claimName: events
      name: events
  license:
    license.lic: |
      FIPS=1
      Mock Connector=1
      SalesForce Connector=1
      ServiceNow Connector=1
      analytics=1
      api_visual_mapper=1
      apiportal=1
      expires=Sun, 07 Dec 2022 11:36:34 GMT
      mcafee=1
      mobile integration=1
      unrestricted=1
      # SIGNATURE: a512a9b3cc28996b7d60232f58ed08bab18945b2b7db4e9d0c442e61cead5519
      # SIGNATURE: 391c9d48b254fe6ec0f93ec23237dc3a35c491ab53a369d375a9b94413b8ea9a
      # SIGNATURE: f9b1776bc91e20868308da83386303d930fe035650e9d3c6106447f9b8fb9cdc
      # SIGNATURE: 90673c5076a69150c2ea8d7a5d3c406d2b7c3a52ffdee876b66793172c7292c3
      # SIGNATURE: 494aa7924ac869d33592f9d075b1cf8c91b70d0c18a8cfbf8c1f0e3356a40b54
      # SIGNATURE: b8bc011ec122bc8c314460cffb2eefc987bc0431f0a9b400574432dbda4ee5f4
      # SIGNATURE: e2ba8b1fb2ce138b3176ebc015b2bb2172bd059ff646d59309e10d93af372174
      # SIGNATURE: 0af7fee3a95535d8ff5f26481499a0add7a481d0a1c44c0075282ea18b33b479


apimgr:
  groupId:
    "MyEmtGroup"
  image:
    repository: "gateway"
    tag: "7.7.0.20221130-3-BN0009-ubi7"
  resources:
    limits:
      memory: "2Gi"
      cpu: 2
    requests:
      memory: "0.5Gi"
      cpu: 0.5
  securityContext:
    runAsNonRoot: false
  route:
    enabled: false
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: apimgr.myexample.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - apimgr.myexample.com
  service:
    port: 8075
  extraVolumeMounts:
    - name: events
      mountPath: /opt/Axway/apigateway/events
  extraVolumes:
    - persistentVolumeClaim:
        claimName: events
      name: events
  license:
    license.lic: |
      FIPS=1
      Mock Connector=1
      SalesForce Connector=1
      ServiceNow Connector=1
      analytics=1
      api_visual_mapper=1
      apiportal=1
      expires=Sun, 07 Dec 2022 11:36:34 GMT
      mcafee=1
      mobile integration=1
      unrestricted=1
      # SIGNATURE: a512a9b3cc28996b7d60232f58ed08bab18945b2b7db4e9d0c442e61cead5519
      # SIGNATURE: 391c9d48b254fe6ec0f93ec23237dc3a35c491ab53a369d375a9b94413b8ea9a
      # SIGNATURE: f9b1776bc91e20868308da83386303d930fe035650e9d3c6106447f9b8fb9cdc
      # SIGNATURE: 90673c5076a69150c2ea8d7a5d3c406d2b7c3a52ffdee876b66793172c7292c3
      # SIGNATURE: 494aa7924ac869d33592f9d075b1cf8c91b70d0c18a8cfbf8c1f0e3356a40b54
      # SIGNATURE: b8bc011ec122bc8c314460cffb2eefc987bc0431f0a9b400574432dbda4ee5f4
      # SIGNATURE: e2ba8b1fb2ce138b3176ebc015b2bb2172bd059ff646d59309e10d93af372174
      # SIGNATURE: 0af7fee3a95535d8ff5f26481499a0add7a481d0a1c44c0075282ea18b33b479
  extraEnvVars:
    - name: EMT_HEALTHCHECK_PORT
      value: "8065"
    - name: EMT_HEALTHCHECK_PATH
      value: /healthcheck
    - name: GW_DIR
      value: /opt/Axway/apigateway
    - name: GW_TRACE_DIR
      value: /opt/Axway/apigateway/groups/topologylinks/emt-group-emt-service/trace
    - name: EMT_TOPOLOGY_TTL
      value: "10"
    - name: EMT_HEAP_SIZE_MB
      value: "1512"
    - name: EMT_TRACE_LEVEL
      value: INFO
    - name: APIGW_LOG_TRACE_TO_FILE
      value: "true"
    - name: APIGW_LOG_TRACE_JSON_TO_STDOUT
      value: "true"
    - name: APIGW_LOG_OPENTRAFFIC_OUTPUT
      value: "file"
    - name: EMT_DEPLOYMENT_ENABLED
      value: "false"
    - name: ACCEPT_GENERAL_CONDITIONS
      value: "yes"

apitraffic:
  image:
    repository: "gateway"
    tag: "7.7.0.20221130-3-BN0009-ubi7"
  resources:
    limits:
      memory: "2Gi"
      cpu: 2
    requests:
      memory: "0.5Gi"
      cpu: 0.5
  securityContext:
    runAsNonRoot: false
  oauth:
    route:
      enabled: false
  route:
    enabled: false
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: apitraffic.myexample.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - apitraffic.myexample.com
  service:
    port: 8065
  extraVolumeMounts:
    - name: events
      mountPath: /opt/Axway/apigateway/events
  extraVolumes:
    - persistentVolumeClaim:
        claimName: events
      name: events
  license:
    license.lic: |
      FIPS=1
      Mock Connector=1
      SalesForce Connector=1
      ServiceNow Connector=1
      analytics=1
      api_visual_mapper=1
      apiportal=1
      expires=Sun, 07 Dec 2022 11:36:34 GMT
      mcafee=1
      mobile integration=1
      unrestricted=1
      # SIGNATURE: a512a9b3cc28996b7d60232f58ed08bab18945b2b7db4e9d0c442e61cead5519
      # SIGNATURE: 391c9d48b254fe6ec0f93ec23237dc3a35c491ab53a369d375a9b94413b8ea9a
      # SIGNATURE: f9b1776bc91e20868308da83386303d930fe035650e9d3c6106447f9b8fb9cdc
      # SIGNATURE: 90673c5076a69150c2ea8d7a5d3c406d2b7c3a52ffdee876b66793172c7292c3
      # SIGNATURE: 494aa7924ac869d33592f9d075b1cf8c91b70d0c18a8cfbf8c1f0e3356a40b54
      # SIGNATURE: b8bc011ec122bc8c314460cffb2eefc987bc0431f0a9b400574432dbda4ee5f4
      # SIGNATURE: e2ba8b1fb2ce138b3176ebc015b2bb2172bd059ff646d59309e10d93af372174
      # SIGNATURE: 0af7fee3a95535d8ff5f26481499a0add7a481d0a1c44c0075282ea18b33b479
  extraEnvVars:
    - name: EMT_HEALTHCHECK_PORT
      value: "8065"
    - name: EMT_HEALTHCHECK_PATH
      value: /healthcheck
    - name: GW_DIR
      value: /opt/Axway/apigateway
    - name: GW_TRACE_DIR
      value: /opt/Axway/apigateway/groups/topologylinks/emt-group-emt-service/trace
    - name: EMT_TOPOLOGY_TTL
      value: "10"
    - name: EMT_HEAP_SIZE_MB
      value: "1512"
    - name: EMT_TRACE_LEVEL
      value: INFO
    - name: APIGW_LOG_TRACE_TO_FILE
      value: "true"
    - name: APIGW_LOG_TRACE_JSON_TO_STDOUT
      value: "true"
    - name: APIGW_LOG_OPENTRAFFIC_OUTPUT
      value: "file"
    - name: EMT_DEPLOYMENT_ENABLED
      value: "false"
    - name: ACCEPT_GENERAL_CONDITIONS
      value: "yes"

aga:
  enabled: false
```